# Generated by Django 3.2 on 2021-12-14 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('center_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'places',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(blank=True, choices=[('펑셔널', '펑셔널'), ('웨이트', '웨이트'), ('바디디자인', '바디디자인'), ('팻버닝', '팻버닝'), ('그룹요가', '그룹요가'), ('그룹복싱', '그룹복싱'), ('그룹필라테스', '그룹필라테스')], max_length=20, null=True)),
                ('pass_count', models.CharField(blank=True, choices=[('10', '10'), ('20', '20'), ('30', '30')], max_length=20, null=True)),
                ('credit', models.DecimalField(blank=True, choices=[('99000', '99000'), ('190000', '190000'), ('290000', '290000'), ('390000', '390000')], decimal_places=0, max_digits=10, null=True)),
                ('closing_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_at', models.TimeField(blank=True, null=True)),
                ('end_at', models.TimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.place')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
