# Generated by Django 3.2 on 2021-12-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
